/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Fabricas.FabricaAbstracta;
import Fabricas.FabricaClockrood;
import Fabricas.FabricaHumano;
import Productos.Arma;
import Productos.Armadura;
import Productos.Cuerpo;
import Productos.CuerpoClockrood;
import Productos.Transporte;


/**
 *
 * @author chris
 */
public class FormClockrood extends javax.swing.JFrame {
    FabricaAbstracta fabrica;
    Cuerpo cuerpo;
    Arma arma;
    Armadura armadura;
    Transporte transporte;
    /**
     * Creates new form FormClockrood
     */
    public FormClockrood() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        fabrica = new FabricaClockrood();
        cuerpo = fabrica.crearCuerpo(); 
        arma = fabrica.crearArma();
        armadura = fabrica.crearArmadura();
        transporte = fabrica.crearTransporte();
        cuerpo = fabrica.crearCuerpo();
        Cuerpo.setIcon(new javax.swing.ImageIcon(getClass().getResource(cuerpo.operacion())));
        Armadura.setIcon(new javax.swing.ImageIcon(getClass().getResource(armadura.operacion())));
        Nave.setIcon(new javax.swing.ImageIcon(getClass().getResource(transporte.operacion())));
        Arma.setIcon(new javax.swing.ImageIcon(getClass().getResource(arma.operacion())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAtras = new javax.swing.JButton();
        Cuerpo = new javax.swing.JLabel();
        Armadura = new javax.swing.JLabel();
        Arma = new javax.swing.JLabel();
        Nave = new javax.swing.JLabel();
        FondoClockrood = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAtras.setBackground(new java.awt.Color(0, 51, 102));
        BotonAtras.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BotonAtras.setForeground(new java.awt.Color(255, 255, 255));
        BotonAtras.setText("ATRAS");
        BotonAtras.setPreferredSize(new java.awt.Dimension(69, 29));
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 803, 110, 50));
        getContentPane().add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 330, 480));
        getContentPane().add(Armadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));
        getContentPane().add(Arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 200, -1, -1));
        getContentPane().add(Nave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        FondoClockrood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClockrood.jpg"))); // NOI18N
        getContentPane().add(FondoClockrood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1628, 885));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        SeleccionarRaza verformulario1=new SeleccionarRaza(); 
 
         //línea 2-hacemos visible el formulario que queremos llamar 
        verformulario1.setVisible(true); 
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClockrood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClockrood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClockrood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClockrood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClockrood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arma;
    private javax.swing.JLabel Armadura;
    private javax.swing.JButton BotonAtras;
    private javax.swing.JLabel Cuerpo;
    private javax.swing.JLabel FondoClockrood;
    private javax.swing.JLabel Nave;
    // End of variables declaration//GEN-END:variables
}
